config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :pairings
end

app/models/pairing.rb
class Pairing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pairings_controller.rb
class PairingsController < ApplicationController
  before_action :set_pairing, only: [:show, :edit, :update, :destroy]

  # GET /pairings
  # GET /pairings.json
  def index
    @pairings = Pairing.all
  end

  # GET /pairings/1
  # GET /pairings/1.json
  def show
  end

  # GET /pairings/new
  def new
    @pairing = Pairing.new
  end

  # GET /pairings/1/edit
  def edit
  end

  # POST /pairings
  # POST /pairings.json
  def create
    @pairing = Pairing.new(pairing_params)

    respond_to do |format|
      if @pairing.save
        format.html { redirect_to @pairing, notice: 'Pairing was successfully created.' }
        format.json { render :show, status: :created, location: @pairing }
      else
        format.html { render :new }
        format.json { render json: @pairing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pairings/1
  # PATCH/PUT /pairings/1.json
  def update
    respond_to do |format|
      if @pairing.update(pairing_params)
        format.html { redirect_to @pairing, notice: 'Pairing was successfully updated.' }
        format.json { render :show, status: :ok, location: @pairing }
      else
        format.html { render :edit }
        format.json { render json: @pairing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pairings/1
  # DELETE /pairings/1.json
  def destroy
    @pairing.destroy
    respond_to do |format|
      format.html { redirect_to pairings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pairing
      @pairing = Pairing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pairing_params
      params.require(:pairing).permit(:from, :till, :student, :teacher, :repo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pairings_helper.rb
module PairingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowPairYou</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pairings/_form.html.erb
<%= form_for(@pairing) do |f| %>
  <% if @pairing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pairing.errors.count, "error") %> prohibited this pairing from being saved:</h2>

      <ul>
      <% @pairing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br>
    <%= f.datetime_select :from %>
  </div>
  <div class="field">
    <%= f.label :till %><br>
    <%= f.datetime_select :till %>
  </div>
  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :repo %><br>
    <%= f.text_field :repo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pairings/edit.html.erb
<h1>Editing pairing</h1>

<%= render 'form' %>

<%= link_to 'Show', @pairing %> |
<%= link_to 'Back', pairings_path %>

app/views/pairings/index.html.erb
<h1>Listing pairings</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Till</th>
      <th>Student</th>
      <th>Teacher</th>
      <th>Repo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pairings.each do |pairing| %>
      <tr>
        <td><%= pairing.from %></td>
        <td><%= pairing.till %></td>
        <td><%= pairing.student %></td>
        <td><%= pairing.teacher %></td>
        <td><%= pairing.repo %></td>
        <td><%= link_to 'Show', pairing %></td>
        <td><%= link_to 'Edit', edit_pairing_path(pairing) %></td>
        <td><%= link_to 'Destroy', pairing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pairing', new_pairing_path %>

app/views/pairings/new.html.erb
<h1>New pairing</h1>

<%= render 'form' %>

<%= link_to 'Back', pairings_path %>

app/views/pairings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @pairing.from %>
</p>

<p>
  <strong>Till:</strong>
  <%= @pairing.till %>
</p>

<p>
  <strong>Student:</strong>
  <%= @pairing.student %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @pairing.teacher %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @pairing.repo %>
</p>

<%= link_to 'Edit', edit_pairing_path(@pairing) %> |
<%= link_to 'Back', pairings_path %>